name: real_image

image_shape: [3, 240, 320]
dataset_path: data/bead_maze

shape_meta: &shape_meta # acceptable types: rgb, low_dim
  obs:
    digit_thumb:
      shape: [1]
      type: low_dim
    digit_index:
      shape: [1]
      type: low_dim
    robot_joint:
      shape: [7]
      type: low_dim
    allegro_joint:
      shape: [16]
      type: low_dim
  action:
    shape: [7]
  allegro_action:
    shape: [16]

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.real_beadmaze_dataset.RealBeadMazeImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null
  delta_action: False
  tactile_input: ${tactile_input}
